version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 5
    rebase-strategy: 'auto'
    commit-message:
      prefix: 'chore(deps)'
    assignees:
      - 'andreasnicolaou'
    versioning-strategy: increase

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'chore(actions)'
    assignees:
      - 'andreasnicolaou'
